// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: cart.proto

package server

import (
	"context"

	"QMall/shoppingCart/cmd/rpc/shoppingcart/internal/logic"
	"QMall/shoppingCart/cmd/rpc/shoppingcart/internal/svc"
	"QMall/shoppingCart/cmd/rpc/shoppingcart/pb"
)

type ShoppingCartServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedShoppingCartServer
}

func NewShoppingCartServer(svcCtx *svc.ServiceContext) *ShoppingCartServer {
	return &ShoppingCartServer{
		svcCtx: svcCtx,
	}
}

func (s *ShoppingCartServer) AddCart(ctx context.Context, in *pb.AddCartReq) (*pb.AddCartResp, error) {
	l := logic.NewAddCartLogic(ctx, s.svcCtx)
	return l.AddCart(in)
}

func (s *ShoppingCartServer) UpdateCart(ctx context.Context, in *pb.UpdateCartReq) (*pb.UpdateCartResp, error) {
	l := logic.NewUpdateCartLogic(ctx, s.svcCtx)
	return l.UpdateCart(in)
}

func (s *ShoppingCartServer) FindCart(ctx context.Context, in *pb.FindCartReq) (*pb.FindCartResp, error) {
	l := logic.NewFindCartLogic(ctx, s.svcCtx)
	return l.FindCart(in)
}

func (s *ShoppingCartServer) GetCarts(ctx context.Context, in *pb.FindCartsReq) (*pb.FindCartsResp, error) {
	l := logic.NewGetCartsLogic(ctx, s.svcCtx)
	return l.GetCarts(in)
}

func (s *ShoppingCartServer) GetCartsByUserId(ctx context.Context, in *pb.FindCartsByUserIdReq) (*pb.FindCartsByUserIdResp, error) {
	l := logic.NewGetCartsByUserIdLogic(ctx, s.svcCtx)
	return l.GetCartsByUserId(in)
}

func (s *ShoppingCartServer) DeleteCartsByUserId(ctx context.Context, in *pb.DeleteCartsByUserIdReq) (*pb.DeleteCartsByUserIdResp, error) {
	l := logic.NewDeleteCartsByUserIdLogic(ctx, s.svcCtx)
	return l.DeleteCartsByUserId(in)
}

func (s *ShoppingCartServer) GetTotalPriceByUserId(ctx context.Context, in *pb.GetTotalPriceByUserIdReq) (*pb.GetTotalPriceByUserIdResp, error) {
	l := logic.NewGetTotalPriceByUserIdLogic(ctx, s.svcCtx)
	return l.GetTotalPriceByUserId(in)
}

func (s *ShoppingCartServer) ShowDetailShoppingCarts(ctx context.Context, in *pb.ShowDetailShoppingCartsReq) (*pb.ShowDetailShoppingCartsResp, error) {
	l := logic.NewShowDetailShoppingCartsLogic(ctx, s.svcCtx)
	return l.ShowDetailShoppingCarts(in)
}
