// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetSecKillQuotaByProductsIdReq struct {
	ProductId int64 `json:"product_id"`
}

type GetSecKillQuotaByProductsIdResp struct {
	SecKillQuota SecKillQuota `json:"secKill_quota"`
}

type IncreaseSecKillOrderReq struct {
	Seller     int64 `gorm:"seller" json:"seller"`           // 买方ID
	Buyer      int64 `gorm:"buyer" json:"buyer"`             // 卖方ID
	ProductsId int64 `gorm:"products_id" json:"products_id"` // 商品ID
	Quantity   int64 `gorm:"quantity" json:"quantity"`       // 秒杀数量
}

type IncreaseSecKillOrderResp struct {
	SecKillActivity  SecKillActivity  `json:"secKill_activity"`
	SecKillOrder     SecKillOrder     `json:"secKill_order"`
	SecKillProducts  SecKillProducts  `json:"secKill_products"`
	SecKillRecord    SecKillRecord    `json:"secKill_record"`
	SecKillUserQuota SecKillUserQuota `json:"secKill_user_quota"`
}

type IncreaseSecKillProductsReq struct {
	ProductId int64   `json:"product_id"`
	Price     float64 `json:"price"`
	Seller    int64   `json:"seller"`
}

type IncreaseSecKillProductsResp struct {
	Seller                    int64                     `json:"seller"`
	SecKillProducts           SecKillProducts           `json:"secKill_products"`
	SecKillActivity           SecKillActivity           `json:"secKill_activity"`
	SecKillActivityProductSku SecKillActivityProductSku `json:"secKill_activity_product_sku"`
}

type IncreaseSecKillQuotaReq struct {
	ProductId   int64 `json:"product_id"`
	LimitNumber int64 `json:"limit_number"`
}

type IncreaseSecKillQuotaResp struct {
	SecKillProducts SecKillProducts `json:"secKill_products"`
	SecKillQuota    SecKillQuota    `json:"secKill_quota"`
}

type IncreaseSecKillRecordReq struct {
	UserId     int64   `gorm:"user_id" json:"user_id"`               // 用户ID
	ProductsId int64   `gorm:"products_id" json:"products_id"`       // 商品ID
	SkuId      int64   `gorm:"product_sku_id" json:"product_sku_id"` // 商品库存ID
	OrderNum   string  `gorm:"order_num" json:"order_num"`           // 订单号
	Price      float64 `gorm:"price" json:"price"`                   // 金额
	Quantity   int64   `gorm:"quantity" json:"quantity"`             // 秒杀数量
}

type IncreaseSecKillRecordResp struct {
	SecKillRecord SecKillRecord `json:"secKill_record"`
}

type IncreaseSecKillStockReq struct {
	ProductsId int64 `gorm:"products_id" json:"products_id"` // 商品ID
	Stock      int64 `gorm:"stock" json:"stock"`             // 库存大小
}

type IncreaseSecKillStockResp struct {
	SecKillStock SecKillStock `json:"secKill_stock"`
}

type IncreaseSecKillUserQuotaReq struct {
	UserId     int64 `gorm:"user_id" json:"user_id"`
	ProductsId int64 `gorm:"products_id" json:"products_id"`
	Num        int64 `gorm:"num" json:"num"`
}

type IncreaseSecKillUserQuotaResp struct {
	SecKillUserQuota SecKillUserQuota `json:"secKill_user_quota"`
}

type SecKillActivity struct {
	ID                int64  `gorm:"primaryKey;column:id" json:"id"`
	Name              string `gorm:"column:name" json:"name"`
	ActivityStartTime string `gorm:"column:activity_start_time" json:"activity_start_time"`
	ActivityEndTime   string `gorm:"column:activity_end_time" json:"activity_end_time"`
	IsOnline          int32  `gorm:"column:is_online" json:"is_online"`
}

type SecKillActivityProduct struct {
	ID                   int64   `gorm:"primaryKey;column:id" json:"id"`
	ActivityTimeID       int64   `gorm:"column:activity_time_id" json:"activity_time_id"`
	ProductID            int64   `gorm:"column:product_id" json:"product_id"`
	ProductName          string  `gorm:"column:product_name" json:"product_name"`
	ProductMainPic       string  `gorm:"column:product_main_picture" json:"product_main_picture"`
	ProductStartingPrice float64 `gorm:"column:product_starting_price" json:"product_starting_price"`
	CategoryID           int64   `gorm:"column:category_id" json:"category_id"`
}

type SecKillActivityProductSku struct {
	ID                int64   `gorm:"primaryKey;column:id" json:"id"`
	ActivityProductID int64   `gorm:"column:activity_product_id" json:"activity_product_id"`
	ProductID         int64   `gorm:"column:product_id" json:"product_id"`
	ProductSkuID      int64   `gorm:"column:product_sku_id" json:"product_sku_id"`
	Price             float64 `gorm:"column:price" json:"price"`
	OriginalPrice     float64 `gorm:"column:original_price" json:"original_price"`
	Number            int64   `gorm:"column:number" json:"number"`
	Stock             int64   `gorm:"column:stock" json:"stock"`
}

type SecKillActivityTime struct {
	ID         int64  `gorm:"primaryKey;column:id" json:"id"`
	ActivityID int64  `gorm:"column:activity_id" json:"activity_id"`
	TimeName   string `gorm:"column:time_name" json:"time_name"`
	StartTime  string `gorm:"column:start_time" json:"start_time"`
	EndTime    string `gorm:"column:end_time" json:"end_time"`
	IsEnable   int32  `gorm:"column:is_enable" json:"is_enable"`
}

type SecKillOrder struct {
	Id          int64  `gorm:"id" json:"id"`                     // ID
	Seller      int64  `gorm:"seller" json:"seller"`             // 买方ID
	Buyer       int64  `gorm:"buyer" json:"buyer"`               // 卖方ID
	ProductsId  int64  `gorm:"products_id" json:"products_id"`   // 商品ID
	ProductsNum string `gorm:"products_num" json:"products_num"` // 商品编号
	OrderNum    string `gorm:"order_num" json:"order_num"`       // 订单号
	Price       string `gorm:"price" json:"price"`               // 金额
	Status      int32  `gorm:"status" json:"status"`             // 状态
	CreateTime  string `gorm:"create_time" json:"create_time"`   // 创建时间
	UpdateTime  string `gorm:"update_time" json:"update_time"`   // 修改时间
}

type SecKillProducts struct {
	Id           int64   `gorm:"id" json:"id"`
	ProductsId   int64   `gorm:"products_id" json:"products_id"`
	ProductsNum  string  `gorm:"products_num" json:"products_num"`   // 商品编号
	ProductsName string  `gorm:"products_name" json:"products_name"` // 商品名字
	Price        float64 `gorm:"price" json:"price"`                 // 价格
	PictureUrl   string  `gorm:"picture_url" json:"picture_url"`     // 商品图片
	Seller       int64   `gorm:"seller" json:"seller"`               // 卖家ID
	CreateTime   string  `gorm:"create_time" json:"create_time"`     // 创建时间
	UpdateTime   string  `gorm:"update_time" json:"update_time"`     // 修改时间
}

type SecKillQuota struct {
	Id                int64  `gorm:"id" json:"id"`
	ProductsId        int64  `gorm:"products_id" json:"products_id"`
	SecKillProductsId int64  `gorm:"seckill_products_id" json:"seckill_products_id"`
	Num               int64  `gorm:"num" json:"num"`
	CreateTime        string `gorm:"create_time" json:"create_time"`
	UpdateTime        string `gorm:"update_time" json:"update_time"`
}

type SecKillRecord struct {
	Id         int64   `gorm:"id" json:"id"`                   // ID
	UserId     int64   `gorm:"user_id" json:"user_id"`         // 用户ID
	ProductsId int64   `gorm:"products_id" json:"products_id"` // 商品ID
	SecNum     string  `gorm:"sec_num" json:"sec_num"`         // 秒杀号
	OrderNum   string  `gorm:"order_num" json:"order_num"`     // 订单号
	Price      float64 `gorm:"price" json:"price"`             // 金额
	Status     int32   `gorm:"status" json:"status"`           // 状态
	CreateTime string  `gorm:"create_time" json:"create_time"` // 创建时间
	UpdateTime string  `gorm:"update_time" json:"update_time"` // 修改时间
}

type SecKillReq struct {
	Seller     int64 `gorm:"seller" json:"seller"`           // 买方ID
	Buyer      int64 `gorm:"buyer" json:"buyer"`             // 卖方ID
	ProductsId int64 `gorm:"products_id" json:"products_id"` // 商品ID//        Price       float64     `gorm:"price" json:"price"`               // 金额
	Quantity   int64 `gorm:"quantity" json:"quantity"`       // 秒杀数量
}

type SecKillResp struct {
	SecKillActivity  SecKillActivity  `json:"secKill_activity"`
	SecKillOrder     SecKillOrder     `json:"secKill_order"`
	SecKillProducts  SecKillProducts  `json:"secKill_products"`
	SecKillRecord    SecKillRecord    `json:"secKill_record"`
	SecKillUserQuota SecKillUserQuota `json:"secKill_user_quota"`
	RemindStock      int64            `json:"remind_stock"`
}

type SecKillStock struct {
	Id         int64  `gorm:"id" json:"id"`                   // ID
	ProductsId int64  `gorm:"products_id" json:"products_id"` // 商品ID
	Stock      int64  `gorm:"stock" json:"stock"`             // 库存大小
	CreateTime string `gorm:"create_time" json:"create_time"` // 创建时间
	UpdateTime string `gorm:"update_time" json:"update_time"` // 修改时间
}

type SecKillUserQuota struct {
	Id         int64  `gorm:"id" json:"id"`
	UserId     int64  `gorm:"user_id" json:"user_id"`
	ProductsId int64  `gorm:"products_id" json:"products_id"`
	Num        int64  `gorm:"num" json:"num"`
	KilledNum  int64  `gorm:"killed_num" json:"killed_num"`
	CreateTime string `gorm:"create_time" json:"create_time"`
	UpdateTime string `gorm:"update_time" json:"update_time"`
}
