// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CreateUserReq struct {
	ClientId int32  `json:"client_id"`
	SystemId int32  `json:"system_id"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type CreateUserResp struct {
}

type DeleteUserReq struct {
	Id int64 `json:"id"`
}

type DeleteUserResp struct {
}

type GetTokenReq struct {
	Uuid string `json:"uuid"`
}

type GetTokenResp struct {
	Token   string `json:"token"`
	IsLogin bool   `json:"isLogin"`
}

type GetUserByIdReq struct {
	Id int64 `json:"id"`
}

type GetUserByIdResp struct {
	User User `json:"user"`
}

type GetUserListReq struct {
}

type GetUserListResp struct {
	UserList []User `json:"users"`
}

type LoginUserReq struct {
	ClientId         int32  `json:"client_id"`
	Phone            string `json:"phone"`
	SystemId         int32  `json:"system_id"`
	VerificationCode string `json:"verificationCode"`
}

type LoginUserResp struct {
	User User `json:"user"`
}

type User struct {
	Id              int64  `json:"id"`
	CreateTime      string `json:"create_time"`
	UpdateTime      string `json:"update_time"`
	IsDeleted       int32  `json:"isDeleted"`
	Account         string `json:"account"`
	Avatar          string `json:"avatar"`
	Gender          int32  `json:"gender"`
	Phone           string `json:"phone"`
	Password        string `json:"password"`
	IDCard          string `json:"id_card"`
	Source          int32  `json:"source"`
	SystemId        int32  `json:"system_id"`
	ClientId        int32  `json:"client_id"`
	UnionId         string `json:"union_id"`
	IsEnable        int32  `json:"is_enable"`
	LastLoginTime   string `json:"last_login_time"`
	CreateUser      int64  `json:"create_user"`
	UpdateUser      int64  `json:"update_user"`
	Token           string `json:"token"`
	SessionId       string `json:"session_id"`
	TokenExpireTime string `json:"token_expire_time"`
}
