// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	seckill "QMall/seckill/cmd/api/desc/seckill/internal/handler/seckill"
	"QMall/seckill/cmd/api/desc/seckill/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 添加秒杀订单
				Method:  http.MethodPost,
				Path:    "/increaseSecKillOrder",
				Handler: seckill.IncreaseSecKillOrderHandler(serverCtx),
			},
			{
				// 添加秒杀商品
				Method:  http.MethodPost,
				Path:    "/increaseSecKillProducts",
				Handler: seckill.IncreaseSecKillProductsHandler(serverCtx),
			},
			{
				// 添加秒杀限额
				Method:  http.MethodPost,
				Path:    "/increaseSecKillQuota",
				Handler: seckill.IncreaseSecKillQuotaHandler(serverCtx),
			},
			{
				// 添加秒杀记录
				Method:  http.MethodPost,
				Path:    "/increaseSecKillRecord",
				Handler: seckill.IncreaseSecKillRecordHandler(serverCtx),
			},
			{
				// 添加秒杀库存
				Method:  http.MethodPost,
				Path:    "/increaseSecKillStock",
				Handler: seckill.IncreaseSecKillStockHandler(serverCtx),
			},
			{
				// 添加秒杀用户限额
				Method:  http.MethodPost,
				Path:    "/increaseSecKillUserQuota",
				Handler: seckill.IncreaseSecKillUserQuotaHandler(serverCtx),
			},
			{
				// 添加秒杀订单V2
				Method:  http.MethodPost,
				Path:    "/secKill",
				Handler: seckill.SecKillHandler(serverCtx),
			},
		},
		rest.WithPrefix("/seckill/v1"),
	)
}
