Name: productSku
Host: 127.0.0.1
Port: 1003
Mode: dev
Mysql:
  Host: "192.168.23.233:3306"
  User: "root"
  Pass: "000000"
  Database: "mall_product"
  Charset: "utf8mb4"
Cache:
  - Host: 192.168.23.233:6379
    Pass: "123456"
ProductSkuRpcConf:
  Endpoints:
    - 127.0.0.1:2003
  NonBlock: true
