// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	shoppingCart "QMall/shoppingCart/cmd/api/desc/shoppingCart/internal/handler/shoppingCart"
	"QMall/shoppingCart/cmd/api/desc/shoppingCart/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 查看购物车
				Method:  http.MethodPost,
				Path:    "/findCart",
				Handler: shoppingCart.FindCartHandler(serverCtx),
			},
			{
				// 添加购物车
				Method:  http.MethodPost,
				Path:    "/increaseCart",
				Handler: shoppingCart.IncreaseCartHandler(serverCtx),
			},
			{
				// 修改购物车
				Method:  http.MethodPost,
				Path:    "/updateCart",
				Handler: shoppingCart.UpdateCartHandler(serverCtx),
			},
		},
		rest.WithPrefix("/shoppingCart/v1"),
	)
}
