// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	tradeOrder "QMall/tradeOrder/cmd/api/desc/tradeOrder/internal/handler/tradeOrder"
	"QMall/tradeOrder/cmd/api/desc/tradeOrder/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 生成订单
				Method:  http.MethodPost,
				Path:    "/addTradeOrder",
				Handler: tradeOrder.AddTradeOrderHandler(serverCtx),
			},
			{
				// 查询订单
				Method:  http.MethodPost,
				Path:    "/findTradeOrder",
				Handler: tradeOrder.FindTradeOrderHandler(serverCtx),
			},
			{
				// 获取订单列表
				Method:  http.MethodGet,
				Path:    "/getTradeOrders",
				Handler: tradeOrder.GetTradeOrdersHandler(serverCtx),
			},
			{
				// 分页获取订单列表
				Method:  http.MethodGet,
				Path:    "/getTradeOrdersByPage",
				Handler: tradeOrder.GetTradeOrdersByPageHandler(serverCtx),
			},
			{
				// 修改订单
				Method:  http.MethodPost,
				Path:    "/updateTradeOrder",
				Handler: tradeOrder.UpdateTradeOrderHandler(serverCtx),
			},
		},
		rest.WithPrefix("/tradeOrder/v1"),
	)
}
