// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type Activity struct {
	ID                int64  `gorm:"primaryKey;column:id" json:"id"`
	Name              string `gorm:"column:name" json:"name"`
	ActivityStartTime string `gorm:"column:activity_start_time" json:"activity_start_time"`
	ActivityEndTime   string `gorm:"column:activity_end_time" json:"activity_end_time"`
	IsOnline          int32  `gorm:"column:is_online" json:"is_online"`
	CreateUser        int64  `gorm:"column:create_user" json:"create_user"`
	CreateTime        string `gorm:"column:create_time" json:"create_time"`
	UpdateUser        int64  `gorm:"column:update_user" json:"update_user"`
	UpdateTime        string `gorm:"column:update_time" json:"update_time"`
	IsDeleted         int32  `gorm:"column:is_deleted" json:"is_deleted"`
}

type ActivityProduct struct {
	ID                   int64   `gorm:"primaryKey;column:id" json:"id"`
	ActivityTimeID       int64   `gorm:"column:activity_time_id" json:"activity_time_id"`
	ProductID            int64   `gorm:"column:product_id" json:"product_id"`
	ProductName          string  `gorm:"column:product_name" json:"product_name"`
	ProductMainPic       string  `gorm:"column:product_main_picture" json:"product_main_picture"`
	ProductStartingPrice float64 `gorm:"column:product_starting_price" json:"product_starting_price"`
	CategoryID           int64   `gorm:"column:category_id" json:"category_id"`
	CreateUser           int64   `gorm:"column:create_user" json:"create_user"`
	CreateTime           string  `gorm:"column:create_time" json:"create_time"`
	UpdateUser           int64   `gorm:"column:update_user" json:"update_user"`
	UpdateTime           string  `gorm:"column:update_time" json:"update_time"`
	IsDeleted            int32   `gorm:"column:is_deleted" json:"is_deleted"`
}

type ActivityProductSku struct {
	ID                int64   `gorm:"primaryKey;column:id" json:"id"`
	ActivityProductID int64   `gorm:"column:activity_product_id" json:"activity_product_id"`
	ProductID         int64   `gorm:"column:product_id" json:"product_id"`
	ProductSkuID      int64   `gorm:"column:product_sku_id" json:"product_sku_id"`
	Price             float64 `gorm:"column:price" json:"price"`
	OriginalPrice     float64 `gorm:"column:original_price" json:"original_price"`
	Number            int64   `gorm:"column:number" json:"number"`
	Stock             int64   `gorm:"column:stock" json:"stock"`
	CreateUser        int64   `gorm:"column:create_user" json:"create_user"`
	CreateTime        string  `gorm:"column:create_time" json:"create_time"`
	UpdateUser        int64   `gorm:"column:update_user" json:"update_user"`
	UpdateTime        string  `gorm:"column:update_time" json:"update_time"`
	IsDeleted         int32   `gorm:"column:is_deleted" json:"is_deleted"`
}

type ActivityTime struct {
	ID         int64  `gorm:"primaryKey;column:id" json:"id"`
	ActivityID int64  `gorm:"column:activity_id" json:"activity_id"`
	TimeName   string `gorm:"column:time_name" json:"time_name"`
	StartTime  string `gorm:"column:start_time" json:"start_time"`
	EndTime    string `gorm:"column:end_time" json:"end_time"`
	IsEnable   int32  `gorm:"column:is_enable" json:"is_enable"`
	CreateUser int64  `gorm:"column:create_user" json:"create_user"`
	CreateTime string `gorm:"column:create_time" json:"create_time"`
	UpdateUser int64  `gorm:"column:update_user" json:"update_user"`
	UpdateTime string `gorm:"column:update_time" json:"update_time"`
	IsDeleted  int32  `gorm:"column:is_deleted" json:"is_deleted"`
}

type AddActivityProductReq struct {
	ActivityTimeId int64 `json:"activity_time_id"`
	ProductId      int64 `json:"product_id"`
	UserId         int64 `json:"user_id"`
}

type AddActivityProductResp struct {
	ActivityProduct ActivityProduct `json:"activity_product"`
}

type AddActivityProductSkuReq struct {
	ActivityProductId int64   `json:"activity_product_id"`
	ProductId         int64   `json:"product_id"`
	ProductSkuId      int64   `json:"product_sku_id"`
	UserId            int64   `json:"user_id"`
	Price             float64 `json:"price"`
	Number            int64   `json:"number"`
}

type AddActivityProductSkuResp struct {
	ActivityProductSku ActivityProductSku `json:"activity_product_sku"`
}

type AddActivityReq struct {
	ActivityName      string `json:"activity_name"`
	IsOnline          int32  `json:"is_online"`
	ActivityStartTime string `json:"activity_start_time"`
	ActivityEndTime   string `json:"activity_end_time"`
	UserId            int64  `json:"user_id"`
}

type AddActivityResp struct {
	Activity Activity `json:"activity"`
}

type AddActivityTimeReq struct {
	ActivityId int64  `json:"activity_id"`
	Name       string `json:"name"`
	UserId     int64  `json:"user_id"`
}

type AddActivityTimeResp struct {
	ActivityId int64    `json:"activity_id"`
	Name       string   `json:"name"`
	UserId     int64    `json:"user_id"`
	Activity   Activity `json:"activity"`
}
