// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	productSku "goZeroDemo4/product/cmd/api/desc/productSku/internal/handler/productSku"
	"goZeroDemo4/product/cmd/api/desc/productSku/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建商品关联
				Method:  http.MethodPost,
				Path:    "/createProductSku",
				Handler: productSku.CreateProductSkuHandler(serverCtx),
			},
			{
				// 根据id删除商品关联
				Method:  http.MethodPost,
				Path:    "/deleteProductSku",
				Handler: productSku.DeleteProductSkuHandler(serverCtx),
			},
			{
				// 根据id获取商品关联
				Method:  http.MethodPost,
				Path:    "/getProductSkuById",
				Handler: productSku.GetProductSkuByIdHandler(serverCtx),
			},
			{
				// 获取商品关联列表
				Method:  http.MethodPost,
				Path:    "/getProductSkus",
				Handler: productSku.GetProductSkusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/productSku/v1"),
	)
}
