// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	activity "QMall/marketing/cmd/api/desc/marketing/internal/handler/activity"
	"QMall/marketing/cmd/api/desc/marketing/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 添加活动表
				Method:  http.MethodPost,
				Path:    "/addActivity",
				Handler: activity.AddActivityHandler(serverCtx),
			},
			{
				// 添加活动商品信息
				Method:  http.MethodPost,
				Path:    "/addActivityProduct",
				Handler: activity.AddActivityProductHandler(serverCtx),
			},
			{
				// 添加活动商品库存信息
				Method:  http.MethodPost,
				Path:    "/addActivityProductSku",
				Handler: activity.AddActivityProductSkuHandler(serverCtx),
			},
			{
				// 添加活动时间表
				Method:  http.MethodPost,
				Path:    "/addActivityTime",
				Handler: activity.AddActivityTimeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/activity/v1"),
	)
}
