// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	user "QMall/user/cmd/api/desc/user/internal/handler/user"
	"QMall/user/cmd/api/desc/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建用户
				Method:  http.MethodPost,
				Path:    "/createUser",
				Handler: user.CreateUserHandler(serverCtx),
			},
			{
				// 根据id删除用户
				Method:  http.MethodPost,
				Path:    "/deleteUser",
				Handler: user.DeleteUserHandler(serverCtx),
			},
			{
				// 根据id获取用户
				Method:  http.MethodPost,
				Path:    "/getUserById",
				Handler: user.GetUserByIdHandler(serverCtx),
			},
			{
				// 分布式Token提取
				Method:  http.MethodPost,
				Path:    "/getUserToken",
				Handler: user.GetUserTokenHandler(serverCtx),
			},
			{
				// 获取用户列表
				Method:  http.MethodPost,
				Path:    "/getUsers",
				Handler: user.GetUsersHandler(serverCtx),
			},
			{
				// 单点用户登录
				Method:  http.MethodPost,
				Path:    "/loginUser",
				Handler: user.LoginUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user/v1"),
	)
}
